### ISSUE TITLE
Change Lambda naming schema to enable longer paths in arc manifests

### ISSUE THREAD

**Issue by ryanblock** [arc-repos/arc-workflows#103]
We've heard a good amount of feedback related to enabling Arc to create longer path names!

## Background
Lambda functions have a 64 character limit for their name. This should be longer, but unfortunately we don't really control that.
<img src="https://user-images.githubusercontent.com/200964/41564582-24db7dea-7308-11e8-9eae-74d5e41446d5.png" width=500>

Our current 25 character limit on paths is derived from creating a human-readable format for Arc-provisioned Lambdas:
```
[app name]-[production|staging]-[get|post|put|patch|delete]-[{path}]
```

Another way of looking at this breakdown:
```
1234567890123456789012345678901234567890123456789012345678901234
____________________-__________-______-_________________________
app name             production delete path
                     staging    patch
                                post
                                put
                                get
```

Thus, the following arc file...
```
@app
architect

@html
post /tasks/:task
```

... creates the following Lambda: `architect-production-post-tasks-000task` (39 chars)

As seen above, another limitation is how we identify Lambdas with path params; since `Function names must contain only letters, numbers, hyphens, or underscores` per AWS's validation rules, the presence of a param (denoted by a `:`) converts to 3 chars (`000`) to aid in their identification.

Thus, a 25 char path limit means a 15 char path of `/:a/:b/:c/:d/:e` actually equates to 25 chars against the Lambda name's limit: `-000a-000b-000c-000d-000e`

## Proposed naming format change
```
[app name]-[p|s]-[get|post|put|patch|del]-[{path}]
```
#### Visualization
```
1234567890123456789012345678901234567890123456789012345678901234
____________________-_-_____-___________________________________
app name             p patch path
                     s post
                       put
                       get
                       del
```
### Differences
- Reduce `production` and `staging` to `p` and `s`; should retain dash delineator to prevent confusion with app name - saves 9 reserved characters
- Truncate `delete` as `del` - saves 1 reserved character

Example Lambda names:
- `architect-p-post-tasks-000task`
- `architect-s-del-tasks-000task`

## Alternate proposed naming format change:
```
[app name]-[p|s]-[g|po|pu|pa|d]-[{path}]
```
#### Visualization
```
1234567890123456789012345678901234567890123456789012345678901234
____________________-_-__-______________________________________
app name             p pa path
                     s po
                       pu
                       g
                       d
```

### Differences
- Further truncates HTTP methods, saving 4 reserved characters:
  - `g` - `get`
  - `po` - `post`
  - `pu` - `put`
  - `pa` - `patch`
  - `d` - `delete`

Example Lambda names:
- `architect-p-po-tasks-000task`
- `architect-s-d-tasks-000task`

---

Would love thoughts (or other ideas!)

**Comment by brianleroux** [comment]
This is really well documented and thought through. 🙏

There are 60+ references to `staging` so, it's doable, but a big change and, most crucial to consider, a breaking change. It's not really userland breaking other than a different naming scheme. We might even be able to be backwards compatible but easier would be to bump the major and projects w architect/workflows would need to migrate thier Lambdas (nuke the inventory and rerun create). Not a huge deal. 

But ideally we find extra length without a break. I have a possible solution. We could limit app name to 10 characters. 

- app name max 10
- env (staging|production) max 10
- http verb (get|put|post|patch|delete) max 6
- path max 35

With dashes that's 64 chars, +10 and backwards compatible with minimal code changes. Makes app naming harder but `@domain` and `#comments` help? 🤔 good tradeoffs discussion. And this is a good class of problem to have! Things are clicking.

**Comment by brianleroux** [comment]
closing for now (new rules in place)
