### ISSUE TITLE
deploy static returns invalid asset paths on success

### ISSUE THREAD

**Issue by kristoferjoseph** [arc-repos/arc-workflows#107]
**Describe the bug**
After a successful run of `npx deploy static`, `arc` outputs incorrect paths to the newly uploaded static assets.

**To Reproduce**
1. Add asset to `.static`
2. run `npx deploy static`
3. Read output
4. See that the urls generated are incorrect 

**Expected behavior**
url for a file named `shipit.png` should be:
`https://s3.us-west-1.amazonaws.com/${bucketName}/shipit.png`

instead of what is output in the terminal:
`https://s3.amazonaws.com/${bucketName}/shipit.png`

**Screenshots**
<img width="235" alt="screen shot 2018-06-29 at 11 38 20 am" src="https://user-images.githubusercontent.com/76308/42108993-fba2fb4c-7b90-11e8-8a7d-c851b1855655.png">

**Desktop (please complete the following information):**
 - OS: all
 - Version `.arc 3.1.19`

**Comment by austinkelleher** [comment]
I'm not currently able to test this, but I think this is as simple as tacking on `process.env.AWS_REGION` to this line: https://github.com/arc-repos/arc-workflows/blob/master/src/deploy/static/_copy-to-s3.js#L45

That line of code should become:

```js
var domain = `https://s3.${process.env.AWS_REGION}.amazonaws.com/`
```
