### ISSUE TITLE
Error behavior in AWS inconsistent with Arc sandbox

### ISSUE THREAD

**Issue by ryanblock** [arc-repos/arc-workflows#111]
Via Marcel in Arc Slack:

---

I'm getting a really weird behaviour
when responding with
```
      res({
        json: {
          error: "Some error"
        }
      });
```

I get a proper json response, of course, with status code 200
as soon as I add status: 200
```
      res({
        json: {
          error: "Some error"
        },
        status: 403
      });
```

The full error response (as shown by curl) is the following:
```
< HTTP/2 403
< content-type: application/json
< content-length: 240
< location: {"json":{"error":"Some error"},"status":403,"cookie":"_idx=-yfkA2D_47_6VXEDTcjndxt2.ViQMxydpMi6co%2FKQamo7BF2CC7MY6%2BrWOHtEystkx08; Max-Age=2319548250281; Path=/; Expires=Fri, 03 Jul 2043 14:57:30 GMT; HttpOnly; Secure; SameSite=Lax","statusCode":403}
< date: Mon, 09 Jul 2018 14:57:30 GMT
< x-amzn-requestid: 66426ba1-8388-11e8-996a-e9a9b32da325
< content-encoding: deflate
< set-cookie:
< x-amz-apigw-id: Jw-p5FBGFiAFdDg=
< x-amzn-trace-id: Root=1-5b4377d8-ebc1918ccd9a4db860e512cb;Sampled=0
< x-cache: Error from cloudfront
< via: 1.1 875b6fcad2dd03c0a755a31d0c745039.cloudfront.net (CloudFront)
< x-amz-cf-id: 6qbQA2j3Taoexpo49-xfag2UBo78Ida_HuydURpup076iOJUtjVfJA==
<
"error":"Some error"},"status":403,"cookie":"_idx=-yfkA2D_47_6VXEDTcjndxt2.ViQMxydpMi6co%2FKQamo7BF2CC7MY6%2BrWOHtEystkx08; Max-Age=2319548250281; Path=/; Expires=Fri, 03 Jul 2043 14:57:30 GMT; HttpOnly; Secure; SameSite=Lax","statusCode":403
```
Using the sandbox does work as expected

**Comment by brianleroux** [comment]
yes I think you're right! I'll try to get this template updated today. its super old code [1] which def needs refactoring. (finding that in the api gateway console is impressive btw / that place is a labyrinth!)

[1] https://github.com/arc-repos/arc-workflows/blob/master/src/create/aws/_create-route/_create-resource/_errors-json.vtl

**Comment by reaktivo** [comment]
That's great to hear. I honestly thought that the mapping config came from AWS itself.

**Comment by brianleroux** [comment]
ok I have a fix, you can either upgrade, delete and recreate the routes (`npx inventory nuke && npx create` or you can patch the effected routes in the console with the following vtl

```vtl
#set($raw = $input.path('$.errorMessage'))
#set($len = $input.path('$.errorMessage').length() - 1)
#set($body = $raw.substring(21, $len))

#set($start = 0)
#set($end = $body.indexOf(',"cookie'))
#set($result = $body.substring($start, $end))

$result
```

Great catch / thx for reporting!
