### ISSUE TITLE
`@aws` section isn't used in `npx deploy`

### ISSUE THREAD

**Issue by jonathanstiansen** [arc-repos/arc-workflows#112]
**Describe the bug**
Running `npx deploy` doesn't read the `@aws` section for profile and/or region.

**To Reproduce**
1. Make new project with a specific `profile` and `region` field in the `.arc` file:
```
@app
myapp

@aws
region us-west-2
profile mynew_profile

@html
get /
```

2. Run `npx create` ensure it works properly, adding the correct route
3. Run `npx deploy` 
4. See error:

```
Deploying 1 lambda                                     
deploy myapp-staging-get-index failed
{ UnrecognizedClientException: The security token included in the request is invalid.
....)
  message: 'The security token included in the request is invalid.',
  code: 'UnrecognizedClientException',
  time: 2018-07-09T20:20:37.906Z,
  requestId: 'xxxxxx-xxxx-xxxx-xxxx-xxxx',
  statusCode: 403,
  retryable: false,
  retryDelay: xx.xxxx }
```

**Expected behavior**
It should deploy.

**Screenshots**
N/A
**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser N/A
 - Command line

**Additional context**
N/A

**Comment by brianleroux** [comment]
sorry for the delay just getting around to this today! tried to reproduce but wan't able to. wondering if this is a shell $PATH lookup thing. 

🕵️‍♂️ Do you have `AWS_PROFILE` and `AWS_REGION` set?

**Comment by jonathanstiansen** [comment]
It doesn't but I thought it doesn't make much sense to have the `@aws` section for profile and/or region if I have to actually make sure I have those env variables set outside of the `.arc` file as well.

**Comment by MasterJames** [comment]
I only recently heard about envrc files. Looking into it it requires installing direnv
https://direnv.net
And a prompt changing entry or similar (changing cd makes more sense to me) in the shell rc script, which checks for working director envrc files and calls them (every time a prompt is output), so it seems to allow different environment variables depending on the working directory.
Not that I'm using it but it seems like it could have some good uses. In this case, it probably makes no difference, still I thought I would mention it.

**Comment by brianleroux** [comment]
Hey @jonathanstiansen we added `@aws` because we increasingly see ppl w multiple accounts but apps tend to only be installed in one. This is classic infra as code thinking: we're versoining the delivery target. 

Weirdly AWS themselves pretty much require those env vars to be set for many things in the `aws-sdk`. So removing that from the default path would cause a lot of problems. Thinking maybe we need better docs here.

**Comment by brianleroux** [comment]
Hey y'all quick update on this. We now default values for both AWS_REGION and AWS_PROFILE so working locally offline should work even if you are on a machine without AWS setup. LMK if you see any issues and we'll jump back on this!

**Comment by mikemaccana** [comment]
Just a quick note the default values (with no env variables set) seem to be broken on `@architect/architect@4.4.12`:

If I remove
```
@aws
region us-east-1
profile default
```
From my `.arc`, `npx deploy` will fail with `UnrecognizedClientException` per this issue.

**Comment by ryanblock** [comment]
Was the project in question deployed at any previously, or was it created for the first time when running `npx deploy`?

**Comment by ryanblock** [comment]
Sorry, brain not working well as I'm a bit sick. Re-reading what you wrote: yes, deploy should fail.

Architect uses some default values, but they're only stubs to get `sandbox` running (as Brian mentioned in August).

As for deploying, though, if you don't pass Architect a region and a profile to use when deploying, what exactly is it deploying to?

Sounds like the issue at hand is that `deploy` needs some better error messaging. Please do feel free to open a separate issue for that!
