### ISSUE TITLE
Sort key in GSI throws error in sandbox

### ISSUE THREAD

**Issue by mrb** [arc-repos/arc-workflows#114]
**Describe the bug**
An `.arc.` file with a sort key in a secondary index raises an error: `ValidationException: Both the Hash Key and the Range Key element in the KeySchema have the same name`

**To Reproduce**
1. Use the following `.arc. file:
```
@app
test-data

@tables
test-indexes
  id *String

@indexes
test-indexes
  status *String
  val **Number
```
2. Run `npx sandbox`

**Expected behavior**
The server should start (this impacts testing too, which is how I found it)

**Desktop (please complete the following information):**
 - Node 10.3.0, NPM 6.1.0, OSX 10.12.2

**Comment by mrb** [comment]
Did some poking around and I think the issue is in here https://github.com/arc-repos/arc-workflows/blob/master/src/sandbox/db/create-table/_get-global-secondary-index.js

**Comment by brianleroux** [comment]
defo bug! thx for triaging that / will have a look hopefully today
