### ISSUE TITLE
new command: npx generate

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/arc-workflows#116]
`npx generate` generates new `.arc` projects

with no args:

- [ ] creates a starter app named `testapp` 
- [ ] has `.arc`, `package.json` and `package-lock.json`
- [ ] `@html` with a single `get /` route
- [ ] `/test` folder with tape setup

with args:

`npx generate https://github.com/arc-repos/arc-example-blog` 

- [ ] copys the above locally
- [ ] supports shortcut syntax `npx generate arc-repos/arc-example-blog`

**Comment by mrb** [comment]
I was on a plane recently and wished I could use a command to generate the code locally for new routes without hitting AWS

**Comment by brianleroux** [comment]
You can! Its poorly documented and possibly has errors but `ARC_LOCAL=yas npx create` should do what you're looking for. (Sorry for busy-ness but we're gonna be back in touch real 🔜 now I promise!!)

**Comment by mrb** [comment]
Busyness rules. I’m patient.

**Comment by brianleroux** [comment]
closing for now; but think we'll have something compelling here 🔜
