### ISSUE TITLE
investigate dynamic header

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/arc-workflows#117]
A new API Gateway capability noticed by @ryanblock should allow us to set both status code and headers dynamically with a little vtl; main goal of this investigation would be to see if we can retain 100% backwards compatibility by adding a new generic interface `@http`.

```.arc
@app
testapp

@http
get /
```

```javascript
// src/http/get-index/index.js
let arc = reqiure('@architect/functions')
let html = '<h1>hi imma four o four</h1>'

function route(req, res) {
  res({
    status: 404,
    headers: {
      'Content-Type': 'text/html; charset=utf8',
      'X-Arc-Example': 'idk-why-but-u-could'
    },
    body: html
  })
}

exports.handler = arc.http(route)
```

Pretty nice! Plain http routes would still support session, middleware, etc.

 https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-override-request-response-parameters.html

**Comment by ryanblock** [comment]
Was just thinking about this feature this morning. Could be so great, and unlock some really sweet new use cases. Looking forward to it!

**Comment by brianleroux** [comment]
it works; not quite dynamic as we have to hardcode the velocity template but the new method sig looks like this:

```javascript
exports.handler = async function http(request) {
  return {
    status: 201,
    cors: true,
    type: 'text/html',
    body: '<b>hi</b>'
  }
}
```
Also supports: `location` and `cookie`. Will document more 🔜
