### ISSUE TITLE
Add support for binary-enabled lambdas to support images

### ISSUE THREAD

**Issue by kborchers** [arc-repos/arc-workflows#12]
https://aws.amazon.com/blogs/compute/binary-support-for-api-integrations-with-amazon-api-gateway/

**Comment by kborchers** [comment]
Wasn't sure if this should go here or in arc-functions

**Comment by brianleroux** [comment]
either way! quick sketch of how this might look in an `.arc` file

```
@img
/assets/img/foo.png # creates an API Gateway route and corresponding lambda handler
/assets/img/bar.jpg
/assets/img/baz.gif
/assets/img/buzz.svg
/assets/img/boom.webp
/assets/img/fav.ico
```

**Comment by brianleroux** [comment]
Gonna close and reference in the wiki
