### ISSUE TITLE
`destroy` command

### ISSUE THREAD

**Issue by filmaj** [arc-repos/arc-workflows#124]
As a relatively new arc user, I am not very familiar with all the various things arc does after I hand over the keys to my AWS account to it. This makes me nervous. I play around with new tools, like arc, to learn them, but I find myself feeling very hesitant to do so with arc because it a) seems to touch many different AWS services and b) I do not have visibility (at this early stage of my use of arc) as to what exactly it does.

What would make me less nervous is a command that would remove all the resources that arc creates in my AWS account. Perhaps based on a project's `.arc` file? I do not know if arc creates AWS resources that are both project-specific as well as "global" (i.e. AWS resources that arc requires regardless of a project's `.arc` file) - so I do not know what the scope of such a command would or could be.

Just a thought 💡

**Comment by ryanblock** [comment]
Hey there! Please see `npx inventory` and `npx inventory nuke`: https://arc.codes/reference/arc-inventory
