### ISSUE TITLE
cli should say `npx dns` instead of `npm run dns`

### ISSUE THREAD

**Issue by filmaj** [arc-repos/arc-workflows#125]
**Describe the bug**
the 'go approve the certificate then rerun this command' instructions likely just need updating to say 'rerun npx dns' instead of 'rerun npm run dns'. I believe this is similar to #79 

**To Reproduce**
1. create a new app with a rando domain name
2. run `npx dns`
3. follow command instructions to the letter, including "rerun `npm run dns`"
4. see error

**Expected behavior**
likely just needs instruction copy update

**~Screenshots~ Logs**
```
➜ npx dns

        ARC_APP_NAME filmaj-api
          AWS_REGION us-west-1
         AWS_PROFILE default

                Node 10.4.1
                 npm 6.2.0
                .arc 3.2.17


Requested certificates for REDACTED
Check domain admin email to verify certs and then rerun npm run dns to continue.

➜ npm run dns
npm ERR! missing script: dns

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/maj/.npm/_logs/2018-08-06T21_13_28_830Z-debug.log
```
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] mac osx
 - Version [e.g. 22] high sierra

**Comment by ryanblock** [comment]
Dope, thank you!

lmk if you want commit privs!
