### ISSUE TITLE
[Bug] npx hydrate failling to hydrate route dependencies

### ISSUE THREAD

**Issue by joemccann** [arc-repos/arc-workflows#126]
**Describe the bug**
When running `npx hydrate`, the `node_modules` folder of my routes are not being populated with their required packages needed.

**To Reproduce**
1. Go to https://github.com/joemccann/begin-functions-app
2. Clone the repo
3. `npm i`
4. `npx hydrate`
5. `cd src/html/get-articles/node_modules`
6. `ls -la`

**Expected behavior**
Upon listing the directory you should see `request-promise` as well as a few other packages that are required in the `index.js` file of the `get-articles` route.  They are not present.

**Screenshots**
Gif of a screen cap here: https://www.dropbox.com/s/bnvkng28tqiqs5z/begin-bug.gif?dl=0

**Desktop (please complete the following information):**
 - OS: MacOS
- npx hydrate output:

```sh
ARC_APP_NAME jump-z3c
AWS_REGION us-west-2
AWS_PROFILE xxx

Node 8.11.1
npm 6.1.0
arc 3.2.18
```

**Comment by brianleroux** [comment]
Ah shitballs! I think its "working" but this is a gotcha. You don't have `request-promise` in your `package.json` here https://github.com/joemccann/begin-functions-app/blob/master/src/html/get-articles/package.json so `npx hydrate` isn't installing it. 

Aside: you should use a smaller http client (like tiny-json-http). It supports promises and, more important, isn't 10mb so it won't impact your Lambda coldstarts!

**Comment by brianleroux** [comment]
np np! hmu if you run into anything weird. Another heads up: we've noticed some funkiness w `package-lock.json` and sadly the easiest way to resolve is to delete it and then rerun `npm i` to regenerate. =/

**Comment by joemccann** [comment]
I npm installed in each lambda and it works fine now.  Closing this.

**Comment by mikemaccana** [comment]
Same issue, same fix: deleting `package-lock.json` and re-running `npm -i`. 👍
