### ISSUE TITLE
npx sandbox should install node_modules

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/arc-workflows#129]
we do this for deploy; no reason we can't do this whenever the sandbox starts. means nobody has to run `npx hydrate` before starting a freshly checked out project (they will still need to run `npm i` however)

**Comment by ryanblock** [comment]
Remembering to run `npx hydrate` is definitely a sticking point, so that would be great – but at what penalty to sandbox start time though? Right now you can kick up a 50+ route app in a couple seconds, whereas `hydrate` will pin your CPU for 45-60+ seconds on that recursive `npm ci`...

**Comment by ryanblock** [comment]
I do love the idea of dealing with this automatically for folks! You’ve def identified something that keeps biting people.

Two states that cause problems: no modules, and changed modules.

Firing hydrate on a route with node modules is def a big improvement.

For changes modules, I wonder if we could deal with that by (ohhhhhh boy) creating a hidden manifest (.arc-packages?) that caches each route’s package.json to compare on startup. If a route’s package.json has changed, rehydrate it, and update the manifest.

Idk, spitballing! But maybe easier than a registry cache...

**Comment by brianleroux** [comment]
yeaaah looked into this a bit more and closing for now; it can't really be done quick as you pointed out and creating a registry a bit of work I'd rather defer to a future person who is hopefully not me ;)

**Comment by ryanblock** [comment]
Hmm, don't tempt me!
