### ISSUE TITLE
Successfully deployed Hello world function returns error

### ISSUE THREAD

**Issue by asunar** [arc-repos/arc-workflows#137]
**Describe the bug**
Running npx create on the quickstart page (https://arc.codes/quickstart/install)
results in an error

**To Reproduce**
1. Follow the instructions at https://arc.codes/quickstart/install 
2. See the successfully deployed ... message
3. Run curl ...
4. See error:
Cannot find module '@architect/functions'

**Expected behavior**
Hello world response

**Screenshots**
```
$ npx create

        ARC_APP_NAME testapp
          AWS_REGION us-west-1
         AWS_PROFILE personal

                Node 8.11.3
                 npm 6.1.0
                .arc 3.4.1


✓ Successfully deployed
https://isqhhm57x3.execute-api.us-west-1.amazonaws.com/staging


$ curl https://isqhhm57x3.execute-api.us-west-1.amazonaws.com/staging
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    44  100    44    0     0     18      0  0:00:02  0:00:02 --:--:--    18

Cannot find module '@architect/functions'
```

**Desktop (please complete the following information):**
 - OS: Windows 10, git bash

**Additional context**
Deleted all existing functions and endpoints under API gateway before running npx create above.

**Comment by brianleroux** [comment]
hmmm, looks like npm isn't installing modules upon deploy. we've had a similar bug in the past. one way to test if the node_modules is missing is to check in the aws console. or you could try `npx deploy` with code like this (taht doesn't use aany modules) to see if it returns anything:

```javascript
exports.handler = function lambda(event, context, callback) {
  callback(null, {html: 'hi from a naked lambda'})
}
```

(if node_modules IS missing … next step would be to diagnose why!) we npm install here:
https://github.com/arc-repos/arc-workflows/blob/master/src/deploy/lambda/02-install-modules.js#L21

(IDK but do you have a way to check for `npm.cmd`? Maybe its missing?)

And we zip things up here:
https://github.com/arc-repos/arc-workflows/blob/master/src/deploy/lambda/_zip-impl.js

Which SHOULD work on windows!

**Comment by ryanblock** [comment]
Closing due to lack of response.

**Comment by twigington** [comment]
I ran into the same issue going through the guide using Win 10 and git bash. After running `npx deploy` the function worked.
