### ISSUE TITLE
`req._static('foo')` doesn't generate proper URL locally

### ISSUE THREAD

**Issue by jonathanstiansen** [arc-repos/arc-workflows#139]
**Describe the bug**
`req._static('foo.png')` according to the [docs](https://arc.codes/guides/static-assets) in the **Linking** section, should produce `localhost:3000/foo.png`. Two problems exist:
1. localhost:3333/img/foo.png **didn't exist** when I was using `workflows 3.2.3` but I upgraded and this started storing the files properly. **so this is fixed**
2. `req._static('/img/foo.png')` produces a non-existent aws url: `https://s3.amazonaws.com/undefined/img/foo.png` - instead of `localhost:333/img/foo.png`

**To Reproduce**
Steps to reproduce the behaviour:
1. add `@static` to project with staging and production options
2. Add assets to `.static` folder
3. Add a `get` html function
4. Add the asset to HTML with `${req._static('/asset/path/img.png')}`
4. Run `npx sandbox`
5. Look in console and see that the path being generated is: `https://s3.amazonaws.com/undefined/asset/path/img.png`

**Expected behavior**
Asset path locally should be `localhost:3333/asset/path/img.png`

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Safari and Chrome

**Additional context**

**Comment by jonathanstiansen** [comment]
This url s3.amazonaws.com wasn't generated with the region in the `.arc` file in production either.

**Comment by ryanblock** [comment]
Yeah, seems clear we need to read the specified AWS region and add that to the `req._static` helper method (possibly among other things).

**Comment by brianleroux** [comment]
should be fixed in `architect/functions 1.9.2` / thx for being patient! (fyi the region style urls not necessary w s3 because bucket names are global to all of s3 anyhow)
