### ISSUE TITLE
Provision API GW methods using uppercase names?

### ISSUE THREAD

**Issue by chids** [arc-repos/arc-workflows#14]
It seems that API GW allows provisioning the method (i.e. HTTP verb) using lowercase and it seems to work fine _except_ when using the in-console test facility. When trying to test a method created as "get" I get...

```json
{
  "cause": "No enum constant com.amazonaws.backplane.executioncore.deployconfig.enums.HttpMethod.get",
  "logref": "e2ed6b96-7516-11e7-afd9-b73280d9a167",
  "message": ""
}
```

...this is, as far as I can tell, obviously a bug in the API GW console but it might not hurt if Arc created methods using all upper case for HTTP verbs?

_(FYI my AWS support case id for this is: 4213986131)_

<img width="1255" alt="api-gw-sad-panda" src="https://user-images.githubusercontent.com/198278/29251437-e8f1c4de-8054-11e7-9101-b846106677c5.png">

**Comment by brianleroux** [comment]
Oh snap! Great catch ---I'll try to get this patched today 🙌

**Comment by brianleroux** [comment]
Plot thickens, if I cast the httpMethod param to uppercase it fails with 

```
NotFoundException: Invalid Method identifier specified
```

(I'll update the forums thread)

**Comment by chids** [comment]
👋, just got this from AWS support:

> _..._
> _I didn't realize that you were using the API to do this or that the API would allow lowercase, but I have tested and confirmed this to be the case. Thanks for bringing that to our attention!_
> 
> _I was able to find that the standards for HTTP methods are indeed required to be case-sensitive and this is defined in RFC 7230, which I have linked for you below: https://tools.ietf.org/html/rfc7230#section-3.1.1_
> 
> _As this is the standard, the request is going to be for us to update our API to convert all methods to upper case moving forward. The only work around is for all parties publishing API's using our API Gateway API to ensure their actions adhere to the above mentioned RFC standards._
>
> _For updates on when this is fixed as well as any other update to AWS you can follow https://aws.amazon.com/new/_
> _..._

**Comment by brianleroux** [comment]
Lol..okaaaay

**Comment by brianleroux** [comment]
Let them know uppercase raises exceptions rn lmao

**Comment by chids** [comment]
> _..._
> _Unfortunately, I was not able to recreate the exact error shown in the post you provided. I was able to use the putMethod document you provided to create a GET method in all caps without issues using the following params<sup>1</sup>:_
> 
```javascript
var params = {
  authorizationType: 'None',
  httpMethod: 'GET',
  resourceId: 'khr3v5hnfe',
  restApiId: '4x4f75ys76',
};
```

> _In addition, I simply placed 'TEST' as the httpMethod and it returned an error which is similar but not the same:_
> `BadRequestException: Invalid HttpMethod specified. Valid options are GET,PUT,POST,DELETE,PATCH,OPTIONS,HEAD,ANY`
> 
> _However, the indication seems to be the same. If I had to guess I would guess that something about that method is getting passed in as a variable in the third parties code and the variable is not getting converted right. However, that's just a best guess kind of scenario as I haven't seen their issue in depth. _
> 
> _What I can say for sure, is that our testing shows the API and SDK successfully constructing a 'GET' method in all caps successfully, as well as a lower case method (unfortunately). It further shows, as noted in my error I provided above, that it is at least verifying the methods are named properly._
> _..._

<sub>[1]: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#putMethod-property</sub>

**Comment by brianleroux** [comment]
=/

Ok, I'll take to forums this afternoon with a failing test case for them.

**Comment by brianleroux** [comment]
Ok nevermind then! It's fixed per the instructions. Interestingly things are not universally upper-cased buuut they do not need to know that. ;)

**Comment by brianleroux** [comment]
Thx again for the help here @chids 💯
