### ISSUE TITLE
CORB blocking static asset GETs

### ISSUE THREAD

**Issue by jonathanstiansen** [arc-repos/arc-workflows#140]
**Describe the bug**
Following the `@static` tutorial does not tell you that you'll need to implement (something, CORS probably?) to use static assets. Perhaps it's because it's detecting the MIME type of the img to be `application/xml`?

**To Reproduce**
1. Create a new arc project on a new account.
2. Add static and the buckets in the `.arc` file
3. Add a resource(s) to `.static` folder.
4. Create a `GET` html endpoint
3. Add said static resource to served HTML in `GET` endpoint.
4. Deploy and navigate to the staging web URL given.
5. See:

```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://s3.amazonaws.com/mybucket-staging/img/myimg.png with MIME type application/xml. See https://www.chromestatus.com/feature/5629709824032768 for more details.
Image (async)
anima_loadAsyncSrcForTag @ (index):97
anima_loadAsyncSrc @ (index):114
(anonymous) @ (index):127
```

**Expected behavior**
Unless something I missed in another tutorial, It's unexpected that a `GET` from my own S3 bucket gets blocked. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome
 - Version 68.0.3440.106

**Additional context**
I checked the mime type for the files in question and the images are set to  `Content-Type | image/png` despite the request believing they are `application/xml`. That's odd unto itself. If you'd like to go to the site to see the messy html and JS feel free: https://ydinwlq9ak.execute-api.us-west-2.amazonaws.com/staging/

**Comment by ryanblock** [comment]
Heya! I think per our 1:1 conversation we discovered that the root cause of this was #139. If I don't have that right, please let me know – otherwise, let's close this issue and focus on fixing #139. Thanks!

**Comment by jonathanstiansen** [comment]
Absolutely correct, sorry about not updating this @ryanblock.

**Comment by ryanblock** [comment]
All good!
