### ISSUE TITLE
During deploys, bubble npm errors and abort

### ISSUE THREAD

**Issue by ryanblock** [arc-repos/arc-workflows#141]
**Describe the bug**
During the deploy workflow, npm-related errors or aborted operations are swallowed. In some cases, Lambdas may be updated that do not include hydrated node_modules directories, causing those functions to completely fail.

**To Reproduce**
Can be difficult to reproduce (i.e. npm is unresponsive or slow). One technique could be to have a present package-lock.json file that is out of sync with the package.json file, which should cause `npm ci` to abort.

**Expected behavior**
We should fail loudly and often when npm-related issues arise, and abort a Lambda deploy instead of letting an update occur that does not include a properly hydrated node_modules folder.

**Comment by brianleroux** [comment]
closing for #151
