### ISSUE TITLE
Deploy from .arc, and not by globbing src dir

### ISSUE THREAD

**Issue by ryanblock** [arc-repos/arc-workflows#142]
**Describe the bug**
When functions are moved or removed, git is likely to leave folders on teammates' machines that contain no function code, but do contain a node_modules folder. (This is expected behavior from git.)

`npx deploy` globs the `src` dir and tries to update any matching Lambdas matching those directories, which may result in deploy errors.

**To Reproduce**
1. Create a function on machine A, push to git
2. Pull from git on machine B
3. Hydrate node modules
4. Move or remove the function on machine A, push to git
5. Pull from git on machine B
6. npx deploy on machine B
7. Likely to see errors re. missing package-lock.json

**Expected behavior**
Src folders that don't appear in the arc manifest should not be attempted to be deployed.

**Comment by brianleroux** [comment]
closing for #151
