### ISSUE TITLE
@app name limited to 10 characters, docs say 20

### ISSUE THREAD

**Issue by sentience** [arc-repos/arc-workflows#153]
**Describe the bug**
When you specify an `@app` name longer than 10 characters, `npx create` produces an error. The [@app documentation](https://arc.codes/reference/app) and [.arc Project Layout documentation](https://arc.codes/quickstart/arc-project-layout) both say the limit is 20 characters.

**To Reproduce**
1. Create a project with .arc file:
    ```
    @app
    this-is-a-test
    
    @json
    get /
    ```
2. Run `npx install`
3. See error

**Expected behavior**
An app name less than 20 characters would work properly, per the documentation.

**Comment by brianleroux** [comment]
ah sorry about that, it was a recent(ish) change and we need to update the docs! 

[some further background if you're curious](https://github.com/arc-repos/arc-workflows/issues/103)
