### ISSUE TITLE
Support @lambdas or @functions for creation of raw lambda functions

### ISSUE THREAD

**Issue by blackcathacker** [arc-repos/arc-workflows#154]
Feature request for arc to support a straight forward raw lambda function. My use case is I want to tie part of an arc application into CodePipeline. While a more specific type of arc lambda could be built, seems as though there could be more use cases where generic lambdas would allow a developer to step outside of arc's abstractions to build other unexpected things where arc or the arc app would not want to concern itself with the trigger mechanism of the lambda.

Suggest adding `@functions` to the `.arc` file definition. These functions would simply export a function or call arc.functions to register itself (not super familiar with the internals yet) and the function would get the typical arguments unmodified from lambda `(event, context, callback)`

**Comment by ryanblock** [comment]
Heya, would @events not suffice? Those basically raw Lambdae, just remove the arc functions boilerplate in index.js.

**Comment by blackcathacker** [comment]
Hmm...apparently that is a decent workaround. Hadn't thought of that.

This still feels like a decent feature though as despite not using it, arc still creates an SNS for that method which in my case should never be triggered.

Thanks for suggestion thought as that definitely unblocks me and does appear to work.

**Comment by ryanblock** [comment]
Yeah, and the nice thing about having that unused SNS (besides the fact that it costs you nothing and doesn't impact performance) is that if you ever do need to publish an event to it later, no additional work required to get it going!

Gonna close for now but if you run into anything specific that requires something even raw-er than `@events` let's def reopen it up and learn more.
