### ISSUE TITLE
Frontend Workflow RFC

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/arc-workflows#19]
- Feature Name: Front End Development Support
- Start Date: 2017-08-25

# Summary
[summary]: #summary

Architect supports `text/html` HTTP endpoints; a well supported frontend development workflow will make working with `architect` easier.

# Motivation
[motivation]: #motivation

To enable frontend developers the ability to build dynamic AWS Lambda based apps as quickly as single page apps can be developed and deployed.

Use cases:

- simple single page apps with a simple script embed
- simple transpiles
- full client side apps with routes and code splitting
- fully 'server' side rendered apps that hydrate client side complete with code splitting

What is the expected outcome?

- setup should be trivial and seamless with existing tooling workflows
- webpack, babel, rollup and browserify should be fully supported with example docs
- deployments should be isolated and immutable
- s3 buckets -> cloudfront distributions -> route53 domains for staging and production
- provisioning and deployment MUST be as fast as the aws rate limits allow

# Guide-level explanation
[guide-level-explanation]: #guide-level-explanation

### Setup

Add `@static` to your `.arc` file:

```arc
@app
testapp

@static
# …has no config! please use this space to instead explain how `npm run build` generates .static
# whats .static? read below!

@domain
wut.click

```

`npm run create` generates S3 buckets

- if `@static` is defined
- create two s3 buckets `appname-staging-static` and `appname-production-static` with CORS * (?)
- adds `.static` to `.gitignore`
- buckets are made web accessible

`npm run dns` sets up static domains

- fails if buckets do not exist
- creates CloudFront Distribution of the previously created S3 buckets
- static.domain.com and static.staging.domain.com are created and CNAME'd to aforementioned cloudfront dist

### Deployment

Devs are encouraged to setup `npm run build` to generate a folder `.static` with their favorite tool. Webpack. Browserify. Rollup or Babel. It doesn't matter as long as you generate `./.static`. Also! `.static` is not checked in.

`npm run deploy static`

- looks for `.static` and skips if it does not exist with a warning
- next checks for an S3 bucket `appname-staging-static/MAJOR.MINOR.PATCH` and halts if it *does* exist warning that it already exists (where `MAJOR.MINOR.PATCH` is derived from the root `package.json`) to ensure immutability of builds
- otherwise uploads contents of `.static` to `appname-staging-static/MAJOR.MINOR.PATCH/`
- finally print urls of deployed artifacts

### Local Development

`npm start`

- starts a static file server for `.static` on localhost:3333 if it exists

# Reference-level explanation
[reference-level-explanation]: #reference-level-explanation

- `npm run create`  generates s3 bukkits
- `npm run dns` generates CloudFront dist and maps to `static.staging.domain.com` and `static.domain.com`
- `npm run deploy static` deploys the contents of `.static` to `static.staging.domain.com/MAJOR.MINOR.PATCH`
- `ARC_DEPLOY=production npm run deploy static` deploys to `static.domain.com/MAJOR.MINOR.PATCH`
- `npm start` serves assets in `.static` on http://localhost:3333

# Drawbacks
[drawbacks]: #drawbacks

Why should we *not* do this?
???

# Rationale and Alternatives
[alternatives]: #alternatives

- Why is this design the best in the space of possible designs?

Alternative designs could invite drawing front end complexity into the arc codebase.

- What other designs have been considered and what is the rationale for not choosing them?

We did consider something higher level that baked in serverside render with clientside hydration complete with code splitting. This proposal is a stepping stone to acheiving that with maximal performance and the flexiblity for the community to roll their own approaches.

- What is the impact of not doing this?

Frontend developers continue deploying single pages applications without the awesome power of a dynamic Node process Lambda behind 'em.

# Unresolved questions
[unresolved]: #unresolved-questions

- What parts of the design do you expect to resolve through the RFC process before this gets merged?
- What parts of the design do you expect to resolve through the implementation of this feature before stabilization?
- What related issues do you consider out of scope for this RFC that could be addressed in the future independently of the solution that comes out of this RFC?

**Comment by davidascher** [comment]
Seems good, but I wonder about the use of `MAJOR.MINOR.PATCH` for versioning over hashes.  What's the motivation? In my experience front-end changes tend to not be manually versioned.

**Comment by brianleroux** [comment]
Hadn't thought about it! 

We package our front end as a node module which exports a single function that accepts a state object and returns a string of the ui for 'serverside' render. We version that and then install into individual lambdas. Then we run a build on that thing that does something similar to the workflows above for the static assets. 

Hash is safer and probably a better idea.

**Comment by brianleroux** [comment]
Ok closing! There is an undocumented stanza `@static` that creates s3 buckets and a companion flow in `npm run deploy` that auto uploads contents in `./.static/` to staging and/or production automatically. Going to create issues for documenting how to use this feature w a build tool like ParcelJS.

**Comment by brianleroux** [comment]
Next features for this: setup static.domain.com and static.staging.domain.com with CloudFront distributions that use the buckets for origins. 🏒
