### ISSUE TITLE
DNS issue - 'Certificate  must be in 'us-east-1' when the AWS_REGION=us-west-2

### ISSUE THREAD

**Issue by jonathanstiansen** [arc-repos/arc-workflows#25]
First thanks for this repo. Really cool idea, and I'd like to use it - thanks for being a good steward of your community by open sourcing this.

On to the question"
When running the `npm run dns` step after getting certificates properly accepted, I get an odd error.

```
$ npm run dns                                                                                                                v6.11.3 | 04:37 pm

> myproj@1.0.0 dns /Users/j/myproj
> AWS_PROFILE=personal-arc AWS_REGION=us-west-2 arc-dns


Found Route53 hosted zone mydomain.com

Please ensure your domain registration is using these nameeservers:
ns-xx.awsdns-x.net.
ns-xx.awsdns-x.co.uk.
ns-xx.awsdns-x.org.
ns-xx.awsdns-x.com.


/Users/j/myproj/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

BadRequestException: Invalid certificate ARN: arn:aws:acm:us-west-2:xxxxx:certificate/xxx-xxx-xxx. Certificate must be in 'us-east-1'.
    at Object.extractError (/Users/j/myproj/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/Users/j/myproj/node_modules/aws-sdk/lib/protocol/rest_json.js:45:8)
    at Request.callListeners (/Users/j/myproj/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/j/myproj/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/j/myproj/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/j/myproj/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/j/myproj/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/j/myproj/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/j/myproj/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/----/myproj/node_modules/aws-sdk/lib/request.js:685:12)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/jono/.nvm/versions/node/v6.11.3/bin/node" "/Users/jono/.nvm/versions/node/v6.11.3/bin/npm" "run" "dns"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! myproj@1.0.0 dns: `AWS_PROFILE=personal-arc AWS_REGION=us-west-2 arc-dns`
npm ERR! Exit status 1
```

Above are the node version and npm version, I'm a bit confused I read [here](https://aws.amazon.com/certificate-manager/faqs/): 

> Q: Can I use the same certificate in more than one AWS Region?
> 
> It depends on whether you’re using Elastic Load Balancing or Amazon CloudFront. To use a certificate with Elastic Load Balancing for the same site (the same fully qualified domain name, or FQDN, or set of FQDNs) in a different Region, you will must request a new certificate for each Region in which you plan to use it. Note that this requires re-validating each name in the certificate for the new Region. To use an ACM certificate with Amazon CloudFront, you must request the certificate in the US East (N. Virginia) region. ACM certificates in this region that are associated with a CloudFront distribution are distributed to all the geographic locations configured for that distribution.

Maybe there is something going on in the background of arc that makes an assumption about zones that don't hold? Or more likely I'm missing something. Any suggestions?

**Comment by brianleroux** [comment]
Oh shit! I forgot about this yes. We need to update the docs to warn about this. API Gateway custom domains can only use certs in `us-east-1` currently. (You can still deploy the API Gateway part to any region / only the certs are limited.)

Good news is you also have an easy fix!

0. Login to the AWS Console
1. Go to AWS Certificate Manager in `us-west-2` and delete the offending certs
2. Change the region to `us-east-1` and generate certs for your domain (eg. mydomain.com and staging.mydomain.com)
3. Rerun `npm run dns` and it should setup the API Gateway mapping using the certs from `us-east-1` in your `us-west-2` API Gateway

LMK how this goes for you!

**Comment by jonathanstiansen** [comment]
@brianleroux thanks! Just to confirm, I did step 3 without changing the region back to us-west-2. 

I did steps 0-2 and it worked fine, though I don't see anything about `staging.mydomain.com`  in the output - do I have to manually do something about that?

Step 3 outputs this (again region for dns command is still `us-east-1`. 

```
Found Route53 hosted zone mydomain.com
...
.../node_modules/aws-sdk/lib/request.js:31
            throw err;

TypeError: Cannot read property 'CertificateArn' of undefined
.../node_modules/@architect/workflows/src/dns/04-create-domain.js:41:96
```

**Comment by jonathanstiansen** [comment]
Next step:

```
.../node_modules/aws-
sdk/lib/request.js:31
            throw err;
            ^

Error: missing api! undefined not found
    at Error (native)
    at Response._list (.../node_modules/@architect/workflows/src/dns/05-create-mapping.js:65:25)
```

I think this may have to do with the fact that I only have two domains names issued, *.mydomain.com and mydomain.com. However, the line in questions is:

line 65:
```
     if (!staging) throw Error(`missing api! ${staging} not found`)
```

Which makes me believe there is some lack of staging creation going on.

**Comment by brianleroux** [comment]
Ok! We're close. Looks like the API Gateway deployments haven't been created yet. (The offending line can't find any.)

Can you make sure you `npm run create` to generate the deployment code and then re-run `npm run dns` ?

**Comment by jonathanstiansen** [comment]
```
[!] $ npm run create                                            v6.11.3 | 02:47 pm

> ...@1.0.0 create /...
> AWS_PROFILE=personal-arc AWS_REGION=us-west-2 arc-create

skip @html code src/html/get-login exists
skip @html worknicer_meraki-production-get-login exists
skip @html worknicer_meraki-staging-get-login exists
skip @tables worknicer_meraki-production-arc-sessions exists
skip @tables worknicer_meraki-staging-arc-sessions exists
skip @scheduled code src/scheduled/log_users_out_of_meraki exists
skip @scheduled ..-staging-log_users_out_of_...exists
skip @scheduled ..-production-log_users_out_of_.. exists
skip @html /login exists
skip @html /login exists
skip @html /login exists
skip @html /login exists


successfully deployed
https://xxx.execute-api.us-west-2.amazonaws.com/staging
https://xxx.execute-api.us-west-2.amazonaws.com/production
```

But then I get the same error when I run `npm run dns`. Could it be because of the mismatch of regions? DNS is east, npm run create is west.

**Comment by brianleroux** [comment]
oh! ya, try switching the `npm run dns` to point at `us-west-1` now that the certs are created (sorry this is super confusing!)

**Comment by jonathanstiansen** [comment]
Doesn't look right, I just replaced it - and it's now re-requesting certs.

**Comment by brianleroux** [comment]
ok lemme see here 1s (also if you wanna move to a more real time comms we have a slack! https://architecture-as-text.slack.com/join/shared_invite/MjE2MzU4Nzg0NTY1LTE1MDA2NzgyMzYtODE2NzRkOGRmYw )

**Comment by brianleroux** [comment]
AHA

I do have a bug here. It should look for certs in us-east-1 only and it doesn't. Gimme a sec and I'll  push a patch.

**Comment by brianleroux** [comment]
Thx for help on this! 💯 🥇 💕
