### ISSUE TITLE
Validate schedule expressions early in the `arc create` process

### ISSUE THREAD

**Issue by davidascher** [arc-repos/arc-workflows#26]
I had invalid schedule expressions in a `sheduled` expression, but arc complained late in the process of creation.  Seems like validating the `.arc` file early would make for a better DX.

`ValidationException: Parameter ScheduleExpression is not valid.`

**Comment by brianleroux** [comment]
super true. have a loooong old todo for this https://github.com/arc-repos/arc-workflows/blob/master/src/create/aws/validate.js

**Comment by brianleroux** [comment]
first pass of fixes for this in `2.7.2` / sorry it took so long! 🍺
