### ISSUE TITLE
Publish newest version (1.1.20)

### ISSUE THREAD

**Issue by austinkelleher** [arc-repos/arc-workflows#27]
Hey, @brianleroux. I'm running into the issue which was fixed here https://github.com/arc-repos/arc-workflows/commit/23489ae6194deb240702efd6f2008deedf3a2d60. You seem to have pushed a new version but it was never published to npm. The latest version on npm is `1.1.19`.

**Comment by brianleroux** [comment]
DOH omg so sorry! Published ❤️
