### ISSUE TITLE
[Proposal] Re-install modules conditionally using environment variable

### ISSUE THREAD

**Issue by austinkelleher** [arc-repos/arc-workflows#35]
## Problem

Currently, when arc-prototype-deploy runs, we install modules using cipm as one of the tasks. This is perfect when running from a CI, but if you're running from your local machine, you may have modules linked in that you do not want to get overwritten.

## Proposal

We could either inspect NODE_ENV or introduce a new environment variable that arc inspects to determine whether the install task should be run. During local development, I would expect that my linked in modules do not get overwritten.

**Comment by brianleroux** [comment]
ya I don't want to break npm but had so many problems with link I wonder if we can encourage our own happy path without configuration / could using `src/shared` for prototyping work ?

**Comment by brianleroux** [comment]
quick update, thinking using our own `src/shared` and recommending against `npm link` based workflows is probably the safest route for now: https://github.com/npm/npm/issues/19421

(once `link` stabilizes we can revisit)

**Comment by brianleroux** [comment]
Closing for now!
