### ISSUE TITLE
Duplicate code in create deployments, not sure which runs

### ISSUE THREAD

**Issue by philnash** [arc-repos/arc-workflows#39]
In trying to add XML support ([progress so far](https://github.com/arc-repos/arc-workflows/compare/master...philnash:xml)), I've come across some code that can _probably_ be deduplicated, but it's not exactly the same. However, I need more information on this.

The two files that are mostly the same are [`src/create/aws/create-html-lambda-deployments/index.js`](https://github.com/arc-repos/arc-workflows/blob/master/src/create/aws/create-html-lambda-deployments/index.js) and [`src/create/aws/create-json-lambda-deployments/index.js`](https://github.com/arc-repos/arc-workflows/blob/master/src/create/aws/create-json-lambda-deployments/index.js).

There are two differences in these files (aside from the strings `"html"` and `"json"`).

* In the JSON version, `_create` [runs a `setTimeout` of 2017 milliseconds](https://github.com/arc-repos/arc-workflows/blob/master/src/create/aws/create-json-lambda-deployments/index.js#L22-L39), but the HTML version runs [straight away](https://github.com/arc-repos/arc-workflows/blob/master/src/create/aws/create-html-lambda-deployments/index.js#L22-L37). Is this timeout necessary?

* The JSON version includes an [`_addApiGatewayInvokePermission`](https://github.com/arc-repos/arc-workflows/blob/master/src/create/aws/create-json-lambda-deployments/index.js#L66-L80) function that runs in the waterfall, but the HTML version doesn't. There is also an identical [`_addApiGatewayInvokePermission` in `02-setup-request.js`](https://github.com/arc-repos/arc-workflows/blob/master/src/create/aws/_create-route/_create-resource/02-setup-request.js#L110-L124). My guess is that the function in `02-setup-request` actually does the job and it's not necessary to run it in the `create-#{type}-lambda-deployments` file too. Can I confirm that? (I'm still working out how to run this in the middle of developing on it, I'll get there, but wanted to ask in case there is anything else to understand about this).

**Comment by brianleroux** [comment]
Hey! Sorry for the delayed response on conference time here ;)

The timeout is def a magic number and usually needed ya. Have a tacit plan to extract that logic as an exponential backoff. Amazon gets aggressive with `TooManyRequestsExceptions` so retrys are unfortunately needed. This *might* go away when we move to AWS SAM and CloudFormation. (If that experiment works out.)

Not sure how the discrepancy happened for the second question… and not sure which matters. :grimacing:

**Comment by brianleroux** [comment]
Hey @philnash sorry to let this go for so long. I'd love a crack at finishing the impl / could you send me a PR with what you have done so far and I can get that going in a branch to flesh out what remains?

**Comment by brianleroux** [comment]
closing because XML is now supported 🎉 

https://arc.codes/reference/xml

thx for hanging in there ;)

**Comment by philnash** [comment]
🎉 Thanks for following up on this! I got way distracted with other things, so thanks for keeping on with it!
