### ISSUE TITLE
As of arc-workflows@2.0 install instructions fail

### ISSUE THREAD

**Issue by jonathanstiansen** [arc-repos/arc-workflows#40]
I tried to update my arc-workflows and got some errors about missing packages.

I attempted to reproduce and here is the result:

```
$ nvm use 6
$ npm init --yes                                                                                                             v6.11.3 | 07:27 am
  npm install @architect/workflows --save
  touch .arc
Wrote to .../test_arc/package.json:

{
  "name": "test_arc",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


test_arc@1.0.0 /.../test_arc
├── @architect/parser@1.0.6  extraneous
├── @smallwins/validate@4.3.0  extraneous
├── aws-sdk@2.163.0  extraneous
├── chalk@1.1.3  extraneous
├── cors@2.8.4  extraneous
├── cp@0.2.0  extraneous
├── cpr@3.0.1  extraneous
├── dynalite@1.2.0  extraneous
├── express@4.16.2  extraneous
├── file-exists@4.0.0  extraneous
├── fs-extra@4.0.2  extraneous
├── lodash.padend@4.6.1  extraneous
├── progress@2.0.0  extraneous
├── run-parallel@1.1.6  extraneous
├── run-waterfall@1.1.3  extraneous
├── slack@9.1.0  extraneous
└── zipit@1.0.2  extraneous

npm WARN test_arc@1.0.0 No description
npm WARN test_arc@1.0.0 No repository field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/jono/.nvm/versions/node/v6.11.3/bin/node" "/Users/jono/.nvm/versions/node/v6.11.3/bin/npm" "install" "@architect/workflows" "--save"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! path /.../test_arc/node_modules/.staging/@iarna/cli-2e39527f
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/.../test_arc/node_modules/.staging/@iarna/cli-2e39527f' -> '/.../test_arc/node_modules/cipm/node_modules/@iarna/cli'
npm ERR! enoent ENOENT: no such file or directory, rename '/.../test_arc/node_modules/.staging/@iarna/cli-2e39527f' -> '/.../test_arc/node_modules/cipm/node_modules/@iarna/cli'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /.../test_arc/npm-debug.log

```

When I use node version 8 it works. Can we use node 8 for `architect` even though lambda only supports `6.10.x`?

**Comment by austinkelleher** [comment]
Hey, @jonathanstiansen. Node 8 is now required with Arc 2.0.0. In the 2.0.0 release, Arc introduced [`cipm`](https://github.com/zkat/cipm) as a dependency and requires `package-lock.json` files, which are only generated using npm 5+.

**Comment by jonathanstiansen** [comment]
Cool then we can close it! :-)

**Comment by jonathanstiansen** [comment]
Hey @austinkelleher just out of curiosity, is it run through babel or something? Can I use node 8 features and still have them work on lambda?

**Comment by austinkelleher** [comment]
@jonathanstiansen Not currently. You could run your code through babel before deploying though by writing a custom babel plugin. Arc now supports plugins (needs documented). Just a quick pseudocode rundown:

```
npm install arc-plugin-babel
```

`.arc` file:
```
...
@plugins
arc-plugin-babel
```

*arc-plugin-babel.js*
```js
module.exports = {
  beforeDeploy (config) {
    // Do the babel compilation here
  }
}
```

**Comment by jonathanstiansen** [comment]
Any reason this isn't an opinionated default? It wouldn't add any runtime dependancies and we'd get nice syntax by default.

**Comment by brianleroux** [comment]
Opinion currently is to stay LTS for tooling and whatever LTS that AWS supports for runtime (6.10) because we don’t want to opt into opaqueness in debugging. Transpiled code is not great for readability and this stuff is hard already!

Moreover opinions are VERY varied in the transpile world and it should be a userland choice to write TypeScript vs Flow vs esnext* —plugins make this trivial and more flexible. 

All that said we need help documenting these trade offs.
