### ISSUE TITLE
Dry-run create folders

### ISSUE THREAD

**Issue by kevinsimper** [arc-repos/arc-workflows#8]
It would make it easier to create small examples and test them locally

**Comment by brianleroux** [comment]
Ah this is a great idea! Maybe this is a new workflow. Create local code only and **do not** generate any AWS infra so you can test stuff out offline. 

Something like `npm run stage` ??

**Comment by kevinsimper** [comment]
`npm run stage` is good, but may not be so initutive if you don't know what it is about like we are talking about now.

Maybe `init` or `setup`?

**Comment by brianleroux** [comment]
`init` sgtm --- will def have a look at adding this if someone doesn't beat me to it

**Comment by brianleroux** [comment]
OK! In the latest version if `ARC_LOCAL` exists `npm run create` only creates local code! This took a minute sorry. =P

**Comment by brianleroux** [comment]
need to do docs but 

```
{
  "name": "test-workflows",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "create": "ARC_LOCAL=yas arc-create",
    "start": "NODE_ENV=testing arc-sandbox"
  },
  "keywords": [],
  "author": "Brian LeRoux <b@brian.io>",
  "license": "Apache-2.0"
}
```

with an `.arc` of 
```
@app
testapp

@html
get /
get /foo
get /baz:bar
```

worked
