### ISSUE TITLE
req._static does not pass through parameter with S3 bucket URL

### ISSUE THREAD

**Issue by ryanblock** [arc-repos/arc-workflows#81]
**To Reproduce**
1. Set up a [`@static` section](https://arc.codes/reference/static) in the Arc project
2. Add `req._static('foo')` to a function (preferably to one deployed to staging or production so you can watch for a non-`localhost` path)
3. Output is `foo`

**Expected behavior**
Output should be `https://s3-{region}.amazonaws.com/{s3 bucket name}/foo`

**Additional context**
Node 8.10
npm 6.0.1

**Comment by brianleroux** [comment]
should be fixed in latest architect/functions
