### ISSUE TITLE
[DX] add a note on wrong npm version if that's the case

### ISSUE THREAD

**Issue by html5cat** [arc-repos/arc-workflows#82]
Just spent a bunch of time debugging why my deploys are not working and lamda sizes are `0.00 mb`. Turns out npm somehow reverted to version 5.6. Would be nice to have a warning for cases like that.
Thanks!

**Comment by brianleroux** [comment]
yea I super agree; will look at adding this in the next release

**Comment by brianleroux** [comment]
fixed!
