### ISSUE TITLE
[DX] node_modules in the lambdas

### ISSUE THREAD

**Issue by html5cat** [arc-repos/arc-workflows#83]
Is there a good way to generate `.gitignore` for lambda functions so that their `node_modules` don't get included in the repo? Thanks

**Comment by html5cat** [comment]
The following `.gitignore` seems to do the trick 🤦‍♂️ 
```
/node_modules/
/src/html/*/node_modules/
```

**Comment by brianleroux** [comment]
closing for now! 👊 💕
