### ISSUE TITLE
node_modules folder is wiped out on npx deploy

### ISSUE THREAD

**Issue by jesusgollonet** [arc-repos/arc-workflows#86]
**Describe the bug**
After creating and initially deploying the project with `npx create`, subsequent runs of `npx deploy` or `npx create` wipe out the node_modules folder for each function, so my lambdas can't even find `@architect/functions`

**To Reproduce**

1. Install following the initial install guide, create your arc file and run `npx create`.
2. After first deployment, run `npx deploy`
3. `ls src/html/get-index/node_modules` will only show an `@architect` folder and any deployed lambda will error out saying it can't find `@architect/functions`

**Expected behavior**
node_modules should not be wiped out.

**Desktop**
 - OSX Sierra
 - arc workflows 2.11.10

**Comment by jesusgollonet** [comment]
For what it's worth i've checked prev versions and at least down to 2.11.8 it does still happen. I checked 2.10.5 since that was the last one before moving to npx and it doesn't happen there (sorry not much time now, will continue later)

**Comment by jesusgollonet** [comment]
Never mind. It turns out i was on npm 5.something, which doesn't have `npm ci` and just failed silently to reinstall modules. User error. Closing this

**Comment by brianleroux** [comment]
thx for the issue tho! need to write validation logic that checks node and npm version! don't hesitate to ping again if you need a hand

**Comment by jesusgollonet** [comment]
Thanks! will def do. love arc!
