### ISSUE TITLE
document `npx hydrate`

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/arc-workflows#88]
new command `npx hydrate` installs node_modules into all lambdas in src

**Comment by brianleroux** [comment]
`npx hydrate update` also!

**Comment by torchhound** [comment]
Should this documentation go in `arc-repos/arc.codes/src/shared/en/aws/guides-deps.md` in addition to a new `npx hydrate` page?

**Comment by brianleroux** [comment]
yes totally
