### ISSUE TITLE
"Error Node@v9.5.0 is not valid; must be 8.10 or higher" prevents npx create

### ISSUE THREAD

**Issue by jesusgollonet** [arc-repos/arc-workflows#89]
**Describe the bug**
Node version checking seems incorrect. I'm getting the message `"Error Node@v9.5.0 is not valid; must be 8.10 or higher"` and i can't `npx create`

**To Reproduce**
1. Using Node 9.5.0, npm 6.1.0 and arc 3.1.0 and the default arc file try to run `npx create`
2. You'll get the error message `"Error Node@v9.5.0 is not valid; must be 8.10 or higher"`

**Expected behavior**
Version checking should recognize node 9.5.0 as higher than 8.10

**versions**
- Node 9.5.0, npm 6.1.0 and arc 3.1.0

**Comment by brianleroux** [comment]
your fix is published in `3.1.1` 

thanks!!!

**Comment by jesusgollonet** [comment]
ah nice! happy to help
