### ISSUE TITLE
Allow dynalite to persist to disk instead of in-memory

### ISSUE THREAD

**Issue by kevinsimper** [arc-repos/arc-workflows#9]
This would make a better development workflow between restarts.

**Comment by brianleroux** [comment]
I'm not sure that it does! This could lead to stale local data conditions. We load mock data and exec a test suite that rebuilds every run. Its 'immutable' this way and keeps the data and logic that acts on it honest as a side effect. 

That said, I'm all for making things easier so lets keep this one open!

**Comment by jondavidjohn** [comment]
I go back and forth, so far in-memory hasn't gotten in my way and will be great for automated testing.

I imagine though once you start building out an app that has even moderately complex state the database getting wiped at every restart (or file change if using something like nodemon) could get cumbersome.

**Comment by kborchers** [comment]
My gut would be to keep the internal functionality in-memory and if someone wants persistent data, they could easily stand up their own instance of dynalite and use that endpoint for testing. I think just adding documentation to that end would be sufficient.

**Comment by brianleroux** [comment]
Closing for now!
