### ISSUE TITLE
Add livereload for npx sandbox

### ISSUE THREAD

**Issue by html5cat** [arc-repos/arc-workflows#94]
If you are currently running `npx sandbox` you need to relaunch it for any code changes to take effect.
Would be awesome to have livereload for for quicker iteration speed 🚤

**Comment by brianleroux** [comment]
gonna leave this as an exercise to the user / we had a look around at the concept but it adds quite a bit to the payload and most devs have their own unique setups for this using babel, typescript or whatever.
