### ISSUE TITLE
Workflows may not respect @aws section when bash vars present

### ISSUE THREAD

**Issue by ryanblock** [arc-repos/arc-workflows#96]
Workflows may not respect an arc file's `@aws` section when bash vars are present. Here's my current setup:

`.bashrc` is exports default arc to my personal profile:
```
export AWS_PROFILE=personal
export AWS_REGION=us-west-1
```

`.aws/credentials` default profile is work:
```
[default]
aws_access_key_id={key id 1}
aws_secret_access_key={secret key 2}
region=us-west-1

[work]
aws_access_key_id={key id 1}
aws_secret_access_key={secret key 1}
region=us-west-1

[personal]
aws_access_key_id={key id 2}
aws_secret_access_key={secret key 2}
region=us-west-1
```

My project is configured to use the work profile:
```
@aws
profile work
region us-west-1
```

When I attempted to run the following workflows from the project dir in question, arc attempted to use the personal profile, and not the `@aws` configured profile:
- `npx create`
- `npx deploy`
- `npx dns`

I was able to work around the issue by changing my `.bashrc` to export work instead of personal, which works fine for me for now since I primarily use arc for work stuff.

Environment
Node 8.11.2
npm 6.1.0
.arc 3.1.9

**Comment by brianleroux** [comment]
eh @ryanblock when you get a chance can you test this again w latest arc-workflows (I think I got it fixed a bit back but need verification)

**Comment by brianleroux** [comment]
like 99% sure this is good now so closing but pls reopen if it happens again!
